#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\AppBundle\Controller\LoginController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

