#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#login:
#     path: /login
#     controller: FOS\UserBundle\Controller::loginAction


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

